<?php
add_carrier('Verizon', "vtext.com");
add_carrier('VMobile', "vmobl.com");
add_carrier('Cingular', "cingularme.com");
add_carrier('Nextel', "messaging.nextel.com");
add_carrier('Alltel', "message.alltel.com");
add_carrier('ATT Mobile', "txt.att.net");
add_carrier('ATT Wireless', "mobile.att.net");
add_carrier('Airpeak', "airpeak.net");
add_carrier('Alaska Com. Systems', "msg.acsalaska.com");
add_carrier('Alaska Wireless', "sms.alaska-wireless.com");
add_carrier('Appalachian Wireless', "awsms.com");
add_carrier('Bluegrass Cellular', "sms.bluecell.com");
add_carrier('Boost Mobile', "myboostmobile.com");
add_carrier('Carolina West', "cwwsms.com");
add_carrier('Cellular South', "csouth1.com");
add_carrier('CellularOne West', "mycellone.com");
add_carrier('CellularOne Dobson', "mobile.celloneusa.com");
add_carrier('Bellsouth', "sms.bellsouth.com");
add_carrier('Cincinatti Bell', "gocbw.com");
add_carrier('Corr Wireless', "corrwireless.net");
add_carrier('Edge Wireless', "sms.edgewireless.com");
add_carrier('EinsteinPCS', "einsteinsms.com");
add_carrier('Inland Cellular', "inlandlink.com");
add_carrier('MetroPCS', "mymetropcs.com");
add_carrier('Midwest Wireless', "clearlydigital.com");
add_carrier('nTelos', "pcs.ntelos.com");
add_carrier('Omnipoint', "mnipoint.com");
add_carrier('Qwest', "qwestmp.com");
add_carrier('SouthernLINC', "page.southernlinc.com");
add_carrier('Sprint', "messaging.sprintpcs.com");
add_carrier('SunCom Wireless', "tms.suncom.com");
add_carrier('Surewest Wireless', "mobile.surewest.com");
add_carrier('T-Mobile Germany', "T-D1-SMS.de");
add_carrier('T-Mobile UK', "t-mobile.uk.net");
add_carrier('T-Mobile USA', "tmomail.net");
add_carrier('Telenor', "mobilpost.no");
add_carrier('Telia Denmark', "gsm1800.telia.dk");
add_carrier('Telus Mobility', "msg.telus.com");
add_carrier('The Phone House', "sms.phonehouse.de");
add_carrier('TIM', "timnet.com");
add_carrier('UMC', "sms.umc.com.ua");
add_carrier('Virgin Mobile Canada', "vmobile.ca");
add_carrier('US Cellular', "email.uscc.net");
add_carrier('Virgin Mobile USA', "vmobl.com");
add_carrier('Vodafone UK', "vodafone.net");
add_carrier('WellCom', "sms.welcome2well.com");
add_carrier('Wyndtell', "wyndtell.com");
add_carrier('Rogers', "pcs.rogers.com");
add_carrier('Cricket', "mms.mycricket.com");
add_carrier('Fido Canada', "fido.ca");
add_carrier('Unicel', "utext.com");
add_carrier('USA Mobility', "usamobility.net");
add_carrier('West Central Wireless', "sms.wcc.net");
add_carrier('Western Wireless', "cellularonewest.com");
add_carrier('Teletouch', "pageme.teletouch.com");
add_carrier('SwissCom', "bluewin.ch");
add_carrier('Sunrise Mobile', "mysunrise.ch");
add_carrier('Southwestern Bell', "email.swbw.com");
add_carrier('Smart Telecom', "mysmart.mymobile.ph");
add_carrier('Skytel Pagers', "skytel.com");
add_carrier('SFR France', "sfr.fr");
add_carrier('Satelink', "satellink.net");
add_carrier('Safaricom', "safaricomsms.com");
add_carrier('Qualcomm', "pager.qualcomm.com");
add_carrier('Primetel', "sms.primtel.ru");
add_carrier('Primeco', "email.uscc.net");
add_carrier('Price Communications', "mobilecell1se.com");
add_carrier('Powertel', "voicestream.net");
add_carrier('Pioneer / Enid', "msg.pioneerenidcellular.com");
add_carrier('PlugGSM', "text.plusgsm.pl");
add_carrier('PCSOne', "pcsone.net");
add_carrier('PageOne Northwest', "page1nw.com");
add_carrier('Pagenet Canada', "pagegate.pagenet.ca");
add_carrier('Pagemart Canada', "pmcl.net");
add_carrier('Movistar', "correo.movistar.net");
add_carrier('Houston Cellular', "text.houstoncellular.net");
add_carrier('Comcast', "comcastpcs.textmsg.com");
add_carrier('Centurytel', "messaging.centurytel.net");
add_carrier('Blue Sky Frog', "blueskyfrog.com");
?>